server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://plovo.c4akum70ou2t.ap-northeast-2.rds.amazonaws.com:3306/oauth_test

    username: admin
    password: 20000118

  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    security:
      oauth2:
        client:
          registration:
            kakao:
              client-id: 08ca26dee47a95cd81776bdad15aec58
              client-secret: DVEJp8VA36mVFgwz8SwJ32Rde0dEcG6d
              redirect-uri: http://localhost:3000/oauth
              authorization-grant-type: authorization_code
              client-authentication-method: POST
              client-name: kakao
              scope:
                - profile_nickname
                - account_email
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id