server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://plovo.c4akum70ou2t.ap-northeast-2.rds.amazonaws.com:3306/oauth_test?useSSL=false&useUnicode=true&characterEncoding=utf8

    username: admin
    password: 20000118

  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    security:
      oauth2:
        client:
          registration:
            kakao:
              client-id: b9f6eaeb47ed2f08476461345671880c
              client-secret: s08zAlut3rrlJIkQRe4AiWNo8rFgtS9j
              redirect-uri: http://52.78.4.217:8080/api/authorization_code
#              redirect-uri: http://localhost:8080/api/authorization_code
              authorization-grant-type: authorization_code
              client-authentication-method: GET
              client-name: kakao
              scope:
                - profile_nickname
                - account_email
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id